version: '3.9'

services:
  app:
    image: apallis/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
